//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaEstudiantil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRERA
    {
        public int IdCarrera { get; set; }
        public string Nombre { get; set; }
        public bool Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioEdicion { get; set; }
        public Nullable<System.DateTime> FechaEdicion { get; set; }
    
        public virtual FACULTAD FACULTAD { get; set; }
    }
}
