//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidaEstudiantil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPRESA()
        {
            this.OFERTALABORAL = new HashSet<OFERTALABORAL>();
        }
    
        public int IdEmpresa { get; set; }
        public string Nombre { get; set; }
        public string AreaDeTrabajo { get; set; }
        public string PaginaWeb { get; set; }
        public bool Estado { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioEdicion { get; set; }
        public Nullable<System.DateTime> FechaEdicion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OFERTALABORAL> OFERTALABORAL { get; set; }
    }
}
