//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIDAESTUDIANTIL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARRERA
    {
        public int IdCarrera { get; set; }
        public string Nombre { get; set; }
        public bool Estado { get; set; }
        public string UsuarioCreacion { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string UsuarioEdicion { get; set; }
        public Nullable<System.DateTime> FechaEdicion { get; set; }
    
        public virtual FACULTAD FACULTAD { get; set; }
    }
}
