USE [master]
GO
/****** Object:  Database [VIDAESTUDIANTIL]    Script Date: 5/25/2023 6:12:47 PM ******/
CREATE DATABASE [VIDAESTUDIANTIL]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'VIDAESTUDIANTIL', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\VIDAESTUDIANTIL.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'VIDAESTUDIANTIL_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\VIDAESTUDIANTIL_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [VIDAESTUDIANTIL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET ARITHABORT OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET  DISABLE_BROKER 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET RECOVERY FULL 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET  MULTI_USER 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET DB_CHAINING OFF 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'VIDAESTUDIANTIL', N'ON'
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET QUERY_STORE = ON
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [VIDAESTUDIANTIL]
GO
/****** Object:  Schema [CURRICULO]    Script Date: 5/25/2023 6:12:47 PM ******/
CREATE SCHEMA [CURRICULO]
GO
/****** Object:  Schema [OFERTALABORAL]    Script Date: 5/25/2023 6:12:47 PM ******/
CREATE SCHEMA [OFERTALABORAL]
GO
/****** Object:  Schema [SISTEMA]    Script Date: 5/25/2023 6:12:47 PM ******/
CREATE SCHEMA [SISTEMA]
GO
/****** Object:  Table [CURRICULO].[CARRERA]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CURRICULO].[CARRERA](
	[IdCarrera] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
	[Estado] [bit] NOT NULL,
	[IdFacultad] [int] NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdCarrera] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CURRICULO].[CERTIFICACION]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CURRICULO].[CERTIFICACION](
	[IdCertificacion] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
	[FechaObtencion] [date] NOT NULL,
	[InstitucionEmisora] [varchar](100) NOT NULL,
	[IdEstudiante] [int] NULL,
	[Estado] [bit] NOT NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdCertificacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CURRICULO].[EDUCACION]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CURRICULO].[EDUCACION](
	[IdEducacion] [int] IDENTITY(1,1) NOT NULL,
	[InstitucionEducativa] [varchar](100) NOT NULL,
	[Titulo] [varchar](100) NOT NULL,
	[FechaInicio] [date] NOT NULL,
	[FechaFinalizacion] [date] NOT NULL,
	[PromedioCalificaciones] [decimal](3, 1) NULL,
	[AreaEstudio] [varchar](100) NULL,
	[IdEstudiante] [int] NULL,
	[Estado] [bit] NOT NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdEducacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CURRICULO].[ESTADOESTUDIANTE]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CURRICULO].[ESTADOESTUDIANTE](
	[IdEstadoEstudiante] [int] IDENTITY(1,1) NOT NULL,
	[Estado] [varchar](20) NOT NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdEstadoEstudiante] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CURRICULO].[ESTUDIANTE]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CURRICULO].[ESTUDIANTE](
	[IdEstudiante] [int] IDENTITY(1,1) NOT NULL,
	[Cif] [int] NOT NULL,
	[Semestre] [int] NULL,
	[FotoPerfil] [varbinary](max) NULL,
	[UltimaModificacion] [date] NOT NULL,
	[Estado] [bit] NOT NULL,
	[IdEstadoEstudiante] [int] NULL,
	[IdUsuario] [int] NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdEstudiante] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [CURRICULO].[ESTUDIANTECARRERA]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CURRICULO].[ESTUDIANTECARRERA](
	[IdEstudianteCarrera] [int] IDENTITY(1,1) NOT NULL,
	[IdEstudiante] [int] NULL,
	[IdCarrera] [int] NULL,
	[Estado] [bit] NOT NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdEstudianteCarrera] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CURRICULO].[EXPERIENCIALABORAL]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CURRICULO].[EXPERIENCIALABORAL](
	[IdExperienciaLaboral] [int] IDENTITY(1,1) NOT NULL,
	[NombreEmpresa] [varchar](50) NOT NULL,
	[Cargo] [varchar](50) NOT NULL,
	[FechaInicio] [date] NOT NULL,
	[FechaFinalizacion] [date] NULL,
	[Telefono] [varchar](20) NULL,
	[Correo] [varchar](100) NULL,
	[IdEstudiante] [int] NULL,
	[Estado] [bit] NOT NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdExperienciaLaboral] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CURRICULO].[FACULTAD]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CURRICULO].[FACULTAD](
	[IdFacultad] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
	[Estado] [bit] NOT NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdFacultad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CURRICULO].[HABILIDAD]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CURRICULO].[HABILIDAD](
	[IdHabilidad] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
	[IdNivelExperiencia] [int] NULL,
	[IdEstudiante] [int] NULL,
	[Estado] [bit] NOT NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdHabilidad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [CURRICULO].[REFERENCIA]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [CURRICULO].[REFERENCIA](
	[IdReferencia] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Apellido] [varchar](50) NOT NULL,
	[Correo] [varchar](100) NOT NULL,
	[Telefono] [varchar](20) NOT NULL,
	[Relacion] [varchar](50) NOT NULL,
	[IdEstudiante] [int] NULL,
	[Estado] [bit] NOT NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdReferencia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [OFERTALABORAL].[DIRECCION]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [OFERTALABORAL].[DIRECCION](
	[IdDireccion] [int] IDENTITY(1,1) NOT NULL,
	[Departamento] [varchar](50) NOT NULL,
	[Municipio] [varchar](50) NOT NULL,
	[Notas] [varchar](300) NULL,
	[Telefono] [varchar](20) NOT NULL,
	[IdEmpresa] [int] NULL,
	[Estado] [bit] NOT NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdDireccion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [OFERTALABORAL].[EMPRESA]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [OFERTALABORAL].[EMPRESA](
	[IdEmpresa] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](100) NOT NULL,
	[AreaDeTrabajo] [varchar](50) NOT NULL,
	[PaginaWeb] [varchar](100) NULL,
	[Estado] [bit] NOT NULL,
	[IdUsuario] [int] NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdEmpresa] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [OFERTALABORAL].[OFERTALABORAL]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [OFERTALABORAL].[OFERTALABORAL](
	[IdOfertaLaboral] [int] IDENTITY(1,1) NOT NULL,
	[Titulo] [varchar](100) NOT NULL,
	[Descripcion] [varchar](300) NOT NULL,
	[IdNivelExperiencia] [int] NULL,
	[Horario] [varchar](50) NOT NULL,
	[Salario] [decimal](10, 2) NOT NULL,
	[Moneda] [varchar](20) NOT NULL,
	[TipoTrabajo] [varchar](20) NOT NULL,
	[Cargo] [varchar](100) NOT NULL,
	[AreaDeTrabajo] [varchar](50) NOT NULL,
	[IdEmpresa] [int] NULL,
	[Estado] [bit] NOT NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdOfertaLaboral] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [OFERTALABORAL].[OFERTALABORALCARRERA]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [OFERTALABORAL].[OFERTALABORALCARRERA](
	[IdOfertaLaboralCarrera] [int] IDENTITY(1,1) NOT NULL,
	[IdOfertaLaboral] [int] NULL,
	[IdCarrera] [int] NULL,
	[Estado] [bit] NOT NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdOfertaLaboralCarrera] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [OFERTALABORAL].[POSTULACION]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [OFERTALABORAL].[POSTULACION](
	[IdPostulacion] [int] IDENTITY(1,1) NOT NULL,
	[IdEstudiante] [int] NULL,
	[IdOfertaLaboral] [int] NULL,
	[Aprobado] [bit] NOT NULL,
	[Estado] [bit] NOT NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdPostulacion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [OFERTALABORAL].[VISTASEMPRESAESTUDIANTE]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [OFERTALABORAL].[VISTASEMPRESAESTUDIANTE](
	[IdVistasEmpresaEstudiante] [int] IDENTITY(1,1) NOT NULL,
	[IdEmpresa] [int] NULL,
	[IdEstudiante] [int] NULL,
	[Cantidad] [int] NOT NULL,
	[UltimaVista] [date] NOT NULL,
	[Estado] [bit] NOT NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdVistasEmpresaEstudiante] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SISTEMA].[NIVELEXPERIENCIA]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SISTEMA].[NIVELEXPERIENCIA](
	[IdNivelExperiencia] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](20) NOT NULL,
	[Estado] [bit] NOT NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdNivelExperiencia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SISTEMA].[OPCION]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SISTEMA].[OPCION](
	[IdOpcion] [int] IDENTITY(1,1) NOT NULL,
	[Descripcion] [varchar](100) NOT NULL,
	[Codigo] [varchar](10) NOT NULL,
	[Estado] [bit] NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdOpcion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SISTEMA].[PERMISOS]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SISTEMA].[PERMISOS](
	[IdPermiso] [int] IDENTITY(1,1) NOT NULL,
	[IdRol] [int] NULL,
	[IdOpcion] [int] NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdPermiso] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SISTEMA].[ROL]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SISTEMA].[ROL](
	[IdRol] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[Estado] [bit] NOT NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdRol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [SISTEMA].[USUARIO]    Script Date: 5/25/2023 6:12:47 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [SISTEMA].[USUARIO](
	[IdUsuario] [int] IDENTITY(1,1) NOT NULL,
	[NombreDeUsuario] [varchar](50) NOT NULL,
	[Nombre] [varchar](50) NOT NULL,
	[SegundoNombre] [varchar](50) NULL,
	[Apellido] [varchar](50) NOT NULL,
	[SegundoApellido] [varchar](50) NULL,
	[Correo] [varchar](50) NOT NULL,
	[Telefono] [varchar](20) NOT NULL,
	[Contrasena] [varchar](20) NOT NULL,
	[IdRol] [int] NULL,
	[Estado] [bit] NOT NULL,
	[UsuarioCreacion] [varchar](50) NULL,
	[FechaCreacion] [datetime] NULL,
	[UsuarioEdicion] [varchar](50) NULL,
	[FechaEdicion] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[IdUsuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [CURRICULO].[FACULTAD] ON 
GO
INSERT [CURRICULO].[FACULTAD] ([IdFacultad], [Nombre], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioEdicion], [FechaEdicion]) VALUES (1, N'Facultad de Ciencias Medicas', 1, N'PAVILION7\PAVILION', CAST(N'2023-05-21T12:37:21.480' AS DateTime), N'PAVILION7\PAVILION', CAST(N'2023-05-21T12:37:21.480' AS DateTime))
GO
INSERT [CURRICULO].[FACULTAD] ([IdFacultad], [Nombre], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioEdicion], [FechaEdicion]) VALUES (2, N'Facultad de Ingeniería y Arquitectura', 1, N'PAVILION7\PAVILION', CAST(N'2023-05-21T15:44:11.133' AS DateTime), N'PAVILION7\PAVILION', CAST(N'2023-05-21T15:44:11.133' AS DateTime))
GO
INSERT [CURRICULO].[FACULTAD] ([IdFacultad], [Nombre], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioEdicion], [FechaEdicion]) VALUES (3, N'Facultad de Odontología', 1, N'PAVILION7\PAVILION', CAST(N'2023-05-21T16:04:39.770' AS DateTime), N'PAVILION7\PAVILION', CAST(N'2023-05-21T16:04:39.770' AS DateTime))
GO
INSERT [CURRICULO].[FACULTAD] ([IdFacultad], [Nombre], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioEdicion], [FechaEdicion]) VALUES (4, N'UAM College', 1, N'PAVILION7\PAVILION', CAST(N'2023-05-24T16:23:53.450' AS DateTime), N'PAVILION7\PAVILION', CAST(N'2023-05-24T16:23:53.450' AS DateTime))
GO
INSERT [CURRICULO].[FACULTAD] ([IdFacultad], [Nombre], [Estado], [UsuarioCreacion], [FechaCreacion], [UsuarioEdicion], [FechaEdicion]) VALUES (5, N'Facultad de Ciencias Jurídicas, Humanidades y Relaciones Internacionales', 1, N'PAVILION7\PAVILION', CAST(N'2023-05-24T16:44:09.423' AS DateTime), N'PAVILION7\PAVILION', CAST(N'2023-05-24T16:44:09.423' AS DateTime))
GO
SET IDENTITY_INSERT [CURRICULO].[FACULTAD] OFF
GO
ALTER TABLE [CURRICULO].[CARRERA] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [CURRICULO].[CARRERA] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [CURRICULO].[CARRERA] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [CURRICULO].[CARRERA] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [CURRICULO].[CARRERA] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [CURRICULO].[CERTIFICACION] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [CURRICULO].[CERTIFICACION] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [CURRICULO].[CERTIFICACION] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [CURRICULO].[CERTIFICACION] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [CURRICULO].[CERTIFICACION] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [CURRICULO].[EDUCACION] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [CURRICULO].[EDUCACION] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [CURRICULO].[EDUCACION] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [CURRICULO].[EDUCACION] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [CURRICULO].[EDUCACION] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [CURRICULO].[ESTADOESTUDIANTE] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [CURRICULO].[ESTADOESTUDIANTE] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [CURRICULO].[ESTADOESTUDIANTE] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [CURRICULO].[ESTADOESTUDIANTE] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [CURRICULO].[ESTUDIANTE] ADD  DEFAULT (getdate()) FOR [UltimaModificacion]
GO
ALTER TABLE [CURRICULO].[ESTUDIANTE] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [CURRICULO].[ESTUDIANTE] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [CURRICULO].[ESTUDIANTE] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [CURRICULO].[ESTUDIANTE] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [CURRICULO].[ESTUDIANTE] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [CURRICULO].[ESTUDIANTECARRERA] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [CURRICULO].[ESTUDIANTECARRERA] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [CURRICULO].[ESTUDIANTECARRERA] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [CURRICULO].[ESTUDIANTECARRERA] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [CURRICULO].[ESTUDIANTECARRERA] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [CURRICULO].[EXPERIENCIALABORAL] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [CURRICULO].[EXPERIENCIALABORAL] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [CURRICULO].[EXPERIENCIALABORAL] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [CURRICULO].[EXPERIENCIALABORAL] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [CURRICULO].[EXPERIENCIALABORAL] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [CURRICULO].[FACULTAD] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [CURRICULO].[FACULTAD] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [CURRICULO].[FACULTAD] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [CURRICULO].[FACULTAD] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [CURRICULO].[FACULTAD] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [CURRICULO].[HABILIDAD] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [CURRICULO].[HABILIDAD] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [CURRICULO].[HABILIDAD] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [CURRICULO].[HABILIDAD] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [CURRICULO].[HABILIDAD] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [CURRICULO].[REFERENCIA] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [CURRICULO].[REFERENCIA] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [CURRICULO].[REFERENCIA] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [CURRICULO].[REFERENCIA] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [CURRICULO].[REFERENCIA] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [OFERTALABORAL].[DIRECCION] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [OFERTALABORAL].[DIRECCION] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [OFERTALABORAL].[DIRECCION] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [OFERTALABORAL].[DIRECCION] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [OFERTALABORAL].[DIRECCION] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [OFERTALABORAL].[EMPRESA] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [OFERTALABORAL].[EMPRESA] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [OFERTALABORAL].[EMPRESA] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [OFERTALABORAL].[EMPRESA] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [OFERTALABORAL].[EMPRESA] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORAL] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORAL] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORAL] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORAL] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORAL] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORALCARRERA] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORALCARRERA] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORALCARRERA] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORALCARRERA] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORALCARRERA] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [OFERTALABORAL].[POSTULACION] ADD  DEFAULT ((0)) FOR [Aprobado]
GO
ALTER TABLE [OFERTALABORAL].[POSTULACION] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [OFERTALABORAL].[POSTULACION] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [OFERTALABORAL].[POSTULACION] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [OFERTALABORAL].[POSTULACION] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [OFERTALABORAL].[POSTULACION] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [OFERTALABORAL].[VISTASEMPRESAESTUDIANTE] ADD  DEFAULT ((0)) FOR [Cantidad]
GO
ALTER TABLE [OFERTALABORAL].[VISTASEMPRESAESTUDIANTE] ADD  DEFAULT (getdate()) FOR [UltimaVista]
GO
ALTER TABLE [OFERTALABORAL].[VISTASEMPRESAESTUDIANTE] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [OFERTALABORAL].[VISTASEMPRESAESTUDIANTE] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [OFERTALABORAL].[VISTASEMPRESAESTUDIANTE] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [OFERTALABORAL].[VISTASEMPRESAESTUDIANTE] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [OFERTALABORAL].[VISTASEMPRESAESTUDIANTE] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [SISTEMA].[NIVELEXPERIENCIA] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [SISTEMA].[NIVELEXPERIENCIA] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [SISTEMA].[NIVELEXPERIENCIA] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [SISTEMA].[NIVELEXPERIENCIA] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [SISTEMA].[NIVELEXPERIENCIA] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [SISTEMA].[OPCION] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [SISTEMA].[OPCION] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [SISTEMA].[OPCION] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [SISTEMA].[OPCION] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [SISTEMA].[OPCION] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [SISTEMA].[PERMISOS] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [SISTEMA].[PERMISOS] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [SISTEMA].[PERMISOS] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [SISTEMA].[PERMISOS] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [SISTEMA].[ROL] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [SISTEMA].[ROL] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [SISTEMA].[ROL] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [SISTEMA].[ROL] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [SISTEMA].[ROL] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [SISTEMA].[USUARIO] ADD  DEFAULT ((1)) FOR [Estado]
GO
ALTER TABLE [SISTEMA].[USUARIO] ADD  DEFAULT (suser_name()) FOR [UsuarioCreacion]
GO
ALTER TABLE [SISTEMA].[USUARIO] ADD  DEFAULT (getdate()) FOR [FechaCreacion]
GO
ALTER TABLE [SISTEMA].[USUARIO] ADD  DEFAULT (suser_name()) FOR [UsuarioEdicion]
GO
ALTER TABLE [SISTEMA].[USUARIO] ADD  DEFAULT (getdate()) FOR [FechaEdicion]
GO
ALTER TABLE [CURRICULO].[CARRERA]  WITH CHECK ADD  CONSTRAINT [FK_FACULTAD_CARRERA] FOREIGN KEY([IdFacultad])
REFERENCES [CURRICULO].[FACULTAD] ([IdFacultad])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [CURRICULO].[CARRERA] CHECK CONSTRAINT [FK_FACULTAD_CARRERA]
GO
ALTER TABLE [CURRICULO].[CERTIFICACION]  WITH CHECK ADD  CONSTRAINT [FK_ESTUDIANTE_CERTIFICACION] FOREIGN KEY([IdEstudiante])
REFERENCES [CURRICULO].[ESTUDIANTE] ([IdEstudiante])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [CURRICULO].[CERTIFICACION] CHECK CONSTRAINT [FK_ESTUDIANTE_CERTIFICACION]
GO
ALTER TABLE [CURRICULO].[EDUCACION]  WITH CHECK ADD  CONSTRAINT [FK_ESTUDIANTE_EDUCACION] FOREIGN KEY([IdEstudiante])
REFERENCES [CURRICULO].[ESTUDIANTE] ([IdEstudiante])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [CURRICULO].[EDUCACION] CHECK CONSTRAINT [FK_ESTUDIANTE_EDUCACION]
GO
ALTER TABLE [CURRICULO].[ESTUDIANTE]  WITH CHECK ADD  CONSTRAINT [FK_ESTADOESTUDIANTE_ESTUDIANTE] FOREIGN KEY([IdEstadoEstudiante])
REFERENCES [CURRICULO].[ESTADOESTUDIANTE] ([IdEstadoEstudiante])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [CURRICULO].[ESTUDIANTE] CHECK CONSTRAINT [FK_ESTADOESTUDIANTE_ESTUDIANTE]
GO
ALTER TABLE [CURRICULO].[ESTUDIANTE]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_ESTUDIANTE] FOREIGN KEY([IdUsuario])
REFERENCES [SISTEMA].[USUARIO] ([IdUsuario])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [CURRICULO].[ESTUDIANTE] CHECK CONSTRAINT [FK_USUARIO_ESTUDIANTE]
GO
ALTER TABLE [CURRICULO].[ESTUDIANTECARRERA]  WITH CHECK ADD  CONSTRAINT [FK_CARRERA_ESTUDIANTECARRERA] FOREIGN KEY([IdCarrera])
REFERENCES [CURRICULO].[CARRERA] ([IdCarrera])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [CURRICULO].[ESTUDIANTECARRERA] CHECK CONSTRAINT [FK_CARRERA_ESTUDIANTECARRERA]
GO
ALTER TABLE [CURRICULO].[ESTUDIANTECARRERA]  WITH CHECK ADD  CONSTRAINT [FK_ESTUDIANTE_ESTUDIANTECARRERA] FOREIGN KEY([IdEstudiante])
REFERENCES [CURRICULO].[ESTUDIANTE] ([IdEstudiante])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [CURRICULO].[ESTUDIANTECARRERA] CHECK CONSTRAINT [FK_ESTUDIANTE_ESTUDIANTECARRERA]
GO
ALTER TABLE [CURRICULO].[EXPERIENCIALABORAL]  WITH CHECK ADD  CONSTRAINT [FK_ESTUDIANTE_EXPERIENCIALABORAL] FOREIGN KEY([IdEstudiante])
REFERENCES [CURRICULO].[ESTUDIANTE] ([IdEstudiante])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [CURRICULO].[EXPERIENCIALABORAL] CHECK CONSTRAINT [FK_ESTUDIANTE_EXPERIENCIALABORAL]
GO
ALTER TABLE [CURRICULO].[HABILIDAD]  WITH CHECK ADD  CONSTRAINT [FK_ESTUDIANTE_HABILIDAD] FOREIGN KEY([IdEstudiante])
REFERENCES [CURRICULO].[ESTUDIANTE] ([IdEstudiante])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [CURRICULO].[HABILIDAD] CHECK CONSTRAINT [FK_ESTUDIANTE_HABILIDAD]
GO
ALTER TABLE [CURRICULO].[HABILIDAD]  WITH CHECK ADD  CONSTRAINT [FK_NIVELEXPERIENCIA_HABILIDAD] FOREIGN KEY([IdNivelExperiencia])
REFERENCES [SISTEMA].[NIVELEXPERIENCIA] ([IdNivelExperiencia])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [CURRICULO].[HABILIDAD] CHECK CONSTRAINT [FK_NIVELEXPERIENCIA_HABILIDAD]
GO
ALTER TABLE [CURRICULO].[REFERENCIA]  WITH CHECK ADD  CONSTRAINT [FK_ESTUDIANTE_REFERENCIA] FOREIGN KEY([IdEstudiante])
REFERENCES [CURRICULO].[ESTUDIANTE] ([IdEstudiante])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [CURRICULO].[REFERENCIA] CHECK CONSTRAINT [FK_ESTUDIANTE_REFERENCIA]
GO
ALTER TABLE [OFERTALABORAL].[DIRECCION]  WITH CHECK ADD  CONSTRAINT [FK_EMPRESA_DIRECCION] FOREIGN KEY([IdEmpresa])
REFERENCES [OFERTALABORAL].[EMPRESA] ([IdEmpresa])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [OFERTALABORAL].[DIRECCION] CHECK CONSTRAINT [FK_EMPRESA_DIRECCION]
GO
ALTER TABLE [OFERTALABORAL].[EMPRESA]  WITH CHECK ADD  CONSTRAINT [FK_USUARIO_EMPRESA] FOREIGN KEY([IdUsuario])
REFERENCES [SISTEMA].[USUARIO] ([IdUsuario])
GO
ALTER TABLE [OFERTALABORAL].[EMPRESA] CHECK CONSTRAINT [FK_USUARIO_EMPRESA]
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORAL]  WITH CHECK ADD  CONSTRAINT [FK_EMPRESA_OFERTALABORAL] FOREIGN KEY([IdEmpresa])
REFERENCES [OFERTALABORAL].[EMPRESA] ([IdEmpresa])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORAL] CHECK CONSTRAINT [FK_EMPRESA_OFERTALABORAL]
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORAL]  WITH CHECK ADD  CONSTRAINT [FK_NIVELEXPERIENCIA_OFERTALABORAL] FOREIGN KEY([IdNivelExperiencia])
REFERENCES [SISTEMA].[NIVELEXPERIENCIA] ([IdNivelExperiencia])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORAL] CHECK CONSTRAINT [FK_NIVELEXPERIENCIA_OFERTALABORAL]
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORALCARRERA]  WITH CHECK ADD  CONSTRAINT [FK_CARRERA_OFERTALABORALCARRERA] FOREIGN KEY([IdCarrera])
REFERENCES [CURRICULO].[CARRERA] ([IdCarrera])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORALCARRERA] CHECK CONSTRAINT [FK_CARRERA_OFERTALABORALCARRERA]
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORALCARRERA]  WITH CHECK ADD  CONSTRAINT [FK_OFERTALABORAL_OFERTALABORALCARRERA] FOREIGN KEY([IdOfertaLaboral])
REFERENCES [OFERTALABORAL].[OFERTALABORAL] ([IdOfertaLaboral])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORALCARRERA] CHECK CONSTRAINT [FK_OFERTALABORAL_OFERTALABORALCARRERA]
GO
ALTER TABLE [OFERTALABORAL].[POSTULACION]  WITH CHECK ADD  CONSTRAINT [FK_ESTUDIANTE_POSTULACION] FOREIGN KEY([IdEstudiante])
REFERENCES [CURRICULO].[ESTUDIANTE] ([IdEstudiante])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [OFERTALABORAL].[POSTULACION] CHECK CONSTRAINT [FK_ESTUDIANTE_POSTULACION]
GO
ALTER TABLE [OFERTALABORAL].[POSTULACION]  WITH CHECK ADD  CONSTRAINT [FK_OFERTALABORAL_POSTULACION] FOREIGN KEY([IdOfertaLaboral])
REFERENCES [OFERTALABORAL].[OFERTALABORAL] ([IdOfertaLaboral])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [OFERTALABORAL].[POSTULACION] CHECK CONSTRAINT [FK_OFERTALABORAL_POSTULACION]
GO
ALTER TABLE [OFERTALABORAL].[VISTASEMPRESAESTUDIANTE]  WITH CHECK ADD  CONSTRAINT [FK_EMPRESA_VISTASEMPRESAESTUDIANTE] FOREIGN KEY([IdEmpresa])
REFERENCES [OFERTALABORAL].[EMPRESA] ([IdEmpresa])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [OFERTALABORAL].[VISTASEMPRESAESTUDIANTE] CHECK CONSTRAINT [FK_EMPRESA_VISTASEMPRESAESTUDIANTE]
GO
ALTER TABLE [OFERTALABORAL].[VISTASEMPRESAESTUDIANTE]  WITH CHECK ADD  CONSTRAINT [FK_ESTUDIANTE_VISTASEMPRESAESTUDIANTE] FOREIGN KEY([IdEstudiante])
REFERENCES [CURRICULO].[ESTUDIANTE] ([IdEstudiante])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [OFERTALABORAL].[VISTASEMPRESAESTUDIANTE] CHECK CONSTRAINT [FK_ESTUDIANTE_VISTASEMPRESAESTUDIANTE]
GO
ALTER TABLE [SISTEMA].[PERMISOS]  WITH CHECK ADD  CONSTRAINT [FK_OPCION_PERMISOS] FOREIGN KEY([IdOpcion])
REFERENCES [SISTEMA].[OPCION] ([IdOpcion])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [SISTEMA].[PERMISOS] CHECK CONSTRAINT [FK_OPCION_PERMISOS]
GO
ALTER TABLE [SISTEMA].[PERMISOS]  WITH CHECK ADD  CONSTRAINT [FK_ROL_PERMISOS] FOREIGN KEY([IdRol])
REFERENCES [SISTEMA].[ROL] ([IdRol])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [SISTEMA].[PERMISOS] CHECK CONSTRAINT [FK_ROL_PERMISOS]
GO
ALTER TABLE [SISTEMA].[USUARIO]  WITH CHECK ADD  CONSTRAINT [FK_ROL_USUARIO] FOREIGN KEY([IdRol])
REFERENCES [SISTEMA].[ROL] ([IdRol])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [SISTEMA].[USUARIO] CHECK CONSTRAINT [FK_ROL_USUARIO]
GO
ALTER TABLE [CURRICULO].[EDUCACION]  WITH CHECK ADD CHECK  (([PromedioCalificaciones]>=(0) AND [PromedioCalificaciones]<=(100)))
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORAL]  WITH CHECK ADD CHECK  (([Moneda]='Cordobas' OR [Moneda]='Dolares'))
GO
ALTER TABLE [OFERTALABORAL].[OFERTALABORAL]  WITH CHECK ADD CHECK  (([TipoTrabajo]='Plazo Fijo' OR [TipoTrabajo]='Pasantia'))
GO
/****** Object:  StoredProcedure [CURRICULO].[GetAllCarrera]    Script Date: 5/25/2023 6:12:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/*Carrera*/
CREATE PROCEDURE [CURRICULO].[GetAllCarrera]
@IDFACULTAD INT
AS
BEGIN
	SELECT c.idCarrera, c.Nombre,c.Estado FROM [CURRICULO].[CARRERA] c
	WHERE IdFacultad=@IDFACULTAD
END
GO
/****** Object:  StoredProcedure [CURRICULO].[GetAllFacultad]    Script Date: 5/25/2023 6:12:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [CURRICULO].[GetAllFacultad]
AS
BEGIN
	SELECT f.IdFacultad,f.Nombre,f.Estado FROM [CURRICULO].[FACULTAD] f
END
GO
/****** Object:  StoredProcedure [CURRICULO].[SaveCarrera]    Script Date: 5/25/2023 6:12:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [CURRICULO].[SaveCarrera]
(
    @NOMBRE VARCHAR(100),
    @IDFACULTAD INT
)
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION

        INSERT INTO [CURRICULO].[CARRERA] (Nombre, IDFACULTAD) VALUES (@NOMBRE, @IDFACULTAD)

        COMMIT
        SELECT 1 AS ESTADO, 'Carrera Guardada Satisfactoriamente' AS MENSAJE
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK

        SELECT 0 AS ESTADO, 'Error al guardar la carrera: ' + ERROR_MESSAGE() AS MENSAJE
    END CATCH
END
GO
/****** Object:  StoredProcedure [CURRICULO].[SaveFacultad]    Script Date: 5/25/2023 6:12:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [CURRICULO].[SaveFacultad]
(
    @NOMBRE VARCHAR(100)
)
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION

        INSERT INTO [CURRICULO].[FACULTAD] (Nombre) VALUES (@NOMBRE)

        COMMIT
        SELECT 1 AS ESTADO, 'Facultad Guardada Satisfactoriamente' AS MENSAJE
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK

        SELECT 0 AS ESTADO, 'Error al guardar la facultad: ' + ERROR_MESSAGE() AS MENSAJE
    END CATCH
END
GO
/****** Object:  StoredProcedure [CURRICULO].[UpdateCarrera]    Script Date: 5/25/2023 6:12:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [CURRICULO].[UpdateCarrera]
(
    @IDCARRERA INT,
    @NOMBRE VARCHAR(100),
    @ESTADO BIT,
    @IDFACULTAD INT
)
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION

        UPDATE [CURRICULO].[CARRERA]
        SET Nombre = @NOMBRE, Estado = @ESTADO, IdFacultad = @IDFACULTAD,UsuarioEdicion = SUSER_NAME(),FechaEdicion = GETDATE()
        WHERE IdCarrera = @IDCARRERA

        COMMIT
        SELECT 1 AS ESTADO, 'Carrera Actualizada Satisfactoriamente' AS MENSAJE
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK

        SELECT 0 AS ESTADO, 'Error al actualizar la carrera: ' + ERROR_MESSAGE() AS MENSAJE
    END CATCH
END
GO
/****** Object:  StoredProcedure [CURRICULO].[UpdateFacultad]    Script Date: 5/25/2023 6:12:48 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [CURRICULO].[UpdateFacultad]
(
    @IDFACULTAD INT,
    @NOMBRE VARCHAR(100),
    @ESTADO BIT
)
AS
BEGIN
    BEGIN TRY
        BEGIN TRANSACTION

        UPDATE [CURRICULO].[FACULTAD]
        SET Nombre = @NOMBRE, Estado = @ESTADO, UsuarioEdicion = SUSER_NAME(), FechaEdicion = GETDATE() 
        WHERE IdFacultad = @IDFACULTAD

        COMMIT
        SELECT 1 AS ESTADO, 'Facultad Actualizada Satisfactoriamente' AS MENSAJE
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK

        SELECT 0 AS ESTADO, 'Error al actualizar la facultad: ' + ERROR_MESSAGE() AS MENSAJE
    END CATCH
END
GO
USE [master]
GO
ALTER DATABASE [VIDAESTUDIANTIL] SET  READ_WRITE 
GO
