/*CREATE DATABASE VIDAESTUDIANTIL

USE VIDAESTUDIANTIL*/


CREATE TABLE USUARIO(
	IdUsuario INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR(50) NOT NULL,
	SegundoNombre VARCHAR(50),
	Apellido VARCHAR(50) NOT NULL,
	SegundoApellido VARCHAR(50),
	Correo VARCHAR(50) NOT NULL,
	Telefono VARCHAR(20) NOT NULL,
	Contrasena VARCHAR(20) NOT NULL,
	Estado BIT DEFAULT 1
)

CREATE TABLE EMPLEADO(
	IdEmpleado INT PRIMARY KEY CONSTRAINT FK_USUARIO_EMPLEADO FOREIGN KEY REFERENCES USUARIO(IdUsuario) ON UPDATE CASCADE ON DELETE CASCADE,
	Estado BIT DEFAULT 1
)

CREATE TABLE ESTADOESTUDIANTE(
	IdEstadoEstudiante INT PRIMARY KEY IDENTITY(1,1),
	Estado VARCHAR(20)
)

CREATE TABLE ESTUDIANTE(
	IdEstudiante INT PRIMARY KEY CONSTRAINT FK_USUARIO_ESTUDIANTE FOREIGN KEY REFERENCES USUARIO(IdUsuario),
	Cif INT NOT NULL,
	Semestre INT,
	FotoPerfil VARBINARY(MAX),
	UltimaModificacion Date,
	Estado BIT DEFAULT 1,
	IdEstadoEstudiante INT CONSTRAINT FK_ESTADOESTUDIANTE_ESTUDIANTE FOREIGN KEY REFERENCES ESTADOESTUDIANTE(IdEstadoEstudiante) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE FACULTAD(
	IdFacultad INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR(100) NOT NULL,
	Estado BIT DEFAULT 1
)

CREATE TABLE CARRERA(
	IdCarrera INT PRIMARY KEY IDENTITY (1,1),
	Nombre VARCHAR(100) NOT NULL,
	Estado BIT DEFAULT 1,
	IdFacultad INT CONSTRAINT FK_FACULTAD_CARRERA FOREIGN KEY REFERENCES FACULTAD(IdFacultad) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE ESTUDIANTECARRERA(
	IdEstudiante INT CONSTRAINT FK_ESTUDIANTE_ESTUDIANTECARRERA FOREIGN KEY REFERENCES ESTUDIANTE(IdEstudiante) ON UPDATE CASCADE ON DELETE CASCADE,
	IdCarrera INT CONSTRAINT FK_CARRERA_ESTUDIANTECARRERA FOREIGN KEY REFERENCES CARRERA(IdCarrera) ON UPDATE CASCADE ON DELETE CASCADE
	CONSTRAINT PK_ESTUDIANTECARRERA PRIMARY KEY(IdEstudiante,IdCarrera)
)

CREATE TABLE EDUCACION(
	IdEducacion INT PRIMARY KEY IDENTITY(1,1),
	InstitucionEducativa VARCHAR(100) NOT NULL,
	Titulo VARCHAR(100) NOT NULL,
	FechaInicio DATE NOT NULL,
	FechaFinalizacion DATE NOT NULL,
	PromedioCalificaciones DECIMAL(3,1) CHECK (PromedioCalificaciones >= 0 AND PromedioCalificaciones <= 100),
	AreaEstudio VARCHAR(100),
	IdEstudiante INT CONSTRAINT FK_ESTUDIANTE_EDUCACION FOREIGN KEY REFERENCES ESTUDIANTE(IdEstudiante) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE NIVELEXPERIENCIA(
	IdNivelExperiencia INT PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(20) NOT NULL
)

CREATE TABLE HABILIDAD(
	IdHabilidad INT PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(100) NOT NULL,
	IdNivelExperiencia INT CONSTRAINT FK_NIVELEXPERIENCIA_HABILIDAD FOREIGN KEY REFERENCES NIVELEXPERIENCIA(IdNivelExperiencia) ON UPDATE CASCADE ON DELETE CASCADE,
	IdEstudiante INT CONSTRAINT FK_ESTUDIANTE_HABILIDAD FOREIGN KEY REFERENCES ESTUDIANTE(IdEstudiante) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE CERTIFICACION(
	IdCertificacion INT PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(100) NOT NULL,
	FechaObtencion DATE NOT NULL,
	InstitucionEmisora VARCHAR(100) NOT NULL,
	IdEstudiante INT CONSTRAINT FK_ESTUDIANTE_CERTIFICACION FOREIGN KEY REFERENCES ESTUDIANTE(IdEstudiante) ON UPDATE CASCADE ON DELETE CASCADE

)

CREATE TABLE REFERENCIA(
	IdReferencia INT PRIMARY KEY IDENTITY(1,1),
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	Correo VARCHAR(100) NOT NULL,
	Telefono VARCHAR(20) NOT NULL,
	Relacion VARCHAR(50) NOT NULL,
	IdEstudiante INT CONSTRAINT FK_ESTUDIANTE_REFERENCIA FOREIGN KEY REFERENCES ESTUDIANTE(IdEstudiante) ON UPDATE CASCADE ON DELETE CASCADE

)

CREATE TABLE EXPERIENCIALABORAL(
	IdExperienciaLaboral INT PRIMARY KEY IDENTITY(1,1),
	NombreTrabajo VARCHAR(50) NOT NULL,
	FechaInicio DATE NOT NULL,
	FechaFinalizacion DATE NOT NULL,
	Telefono VARCHAR(20) NOT NULL,
	IdEstudiante INT CONSTRAINT FK_ESTUDIANTE_EXPERIENCIALABORAL FOREIGN KEY REFERENCES ESTUDIANTE(IdEstudiante) ON UPDATE CASCADE ON DELETE CASCADE

)

CREATE TABLE EMPRESA(
	IdEmpresa INT PRIMARY KEY CONSTRAINT FK_USUARIO_EMPRESA FOREIGN KEY REFERENCES USUARIO(IdUsuario),
	Nombre VARCHAR(100) NOT NULL,
	AreaDeTrabajo VARCHAR(50) NOT NULL,
	PaginaWeb VARCHAR(100),
	Estado BIT DEFAULT 1
)

CREATE TABLE DIRECCION(
	IdDireccion INT PRIMARY KEY IDENTITY(1,1),
	Departamento VARCHAR(50) NOT NULL,
	Municipio VARCHAR(50) NOT NULL,
	Notas VARCHAR(300),
	Telefono VARCHAR(20) NOT NULL,
	IdEmpresa INT CONSTRAINT FK_EMPRESA_DIRECCION FOREIGN KEY REFERENCES EMPRESA(IdEmpresa) ON UPDATE CASCADE ON DELETE CASCADE
)

CREATE TABLE OFERTALABORAL(
	IdOfertaLaboral INT PRIMARY KEY IDENTITY(1,1),
	Titulo VARCHAR(100) NOT NULL,
	Descripcion VARCHAR(300) NOT NULL,
	IdNivelExperiencia INT CONSTRAINT FK_NIVELEXPERIENCIA_OFERTALABORAL FOREIGN KEY REFERENCES NIVELEXPERIENCIA(IdNivelExperiencia) ON UPDATE CASCADE ON DELETE CASCADE,
	Horario VARCHAR(50) NOT NULL,
	Salario DECIMAL(10,2) NOT NULL,
	TipoTrabajo VARCHAR(20) CHECK (TipoTrabajo IN('Pasantia','Plazo Fijo')) NOT NULL,
	FechaVigencia DATE NOT NULL,
	Cargo VARCHAR(100) NOT NULL,
	AreaDeTrabajo VARCHAR(50) NOT NULL,
	IdEmpresa INT CONSTRAINT FK_EMPRESA_OFERTALABORAL FOREIGN KEY REFERENCES EMPRESA(IdEmpresa) ON UPDATE CASCADE ON DELETE CASCADE,
	Estado BIT DEFAULT 1
)

CREATE TABLE OFERTALABORALCARRERA(
	IdOfertaLaboral INT CONSTRAINT FK_OFERTALABORAL_OFERTALABORALCARRERA FOREIGN KEY REFERENCES OFERTALABORAL(IdOfertaLaboral) ON UPDATE CASCADE ON DELETE CASCADE,
	IdCarrera INT CONSTRAINT FK_CARRERA_OFERTALABORALCARRERA FOREIGN KEY REFERENCES CARRERA(IdCarrera) ON UPDATE CASCADE ON DELETE CASCADE
	CONSTRAINT PK_OFERTALABORALCARRERA PRIMARY KEY(IdOfertaLaboral,IdCarrera)
)

CREATE TABLE VISTASEMPRESAESTUDIANTE(
	IdEmpresa INT CONSTRAINT FK_EMPRESA_VISTASEMPRESAESTUDIANTE FOREIGN KEY REFERENCES EMPRESA(IdEmpresa) ON UPDATE CASCADE ON DELETE CASCADE,
	IdEstudiante INT CONSTRAINT FK_ESTUDIANTE_VISTASEMPRESAESTUDIANTE FOREIGN KEY REFERENCES ESTUDIANTE(IdEstudiante) ON UPDATE CASCADE ON DELETE CASCADE,
	Cantidad INT DEFAULT 0,
	UltimaVista DATE,
	CONSTRAINT PK_VISTASEMPRESAESTUDIANTE PRIMARY KEY(IdEmpresa,IdEstudiante)
)

CREATE TABLE POSTULACION(
	IdEstudiante INT CONSTRAINT FK_ESTUDIANTE_POSTULACION FOREIGN KEY REFERENCES ESTUDIANTE(IdEstudiante) ON UPDATE CASCADE ON DELETE CASCADE,
	IdOfertaLaboral INT CONSTRAINT FK_OFERTALABORAL_POSTULACION FOREIGN KEY REFERENCES OFERTALABORAL(IdOfertaLaboral) ON UPDATE CASCADE ON DELETE CASCADE,
	Aprobado BIT DEFAULT 0,
	CONSTRAINT PK_POSTULACION PRIMARY KEY(IdEstudiante,IdOfertaLaboral)
)
/*
CREATE SCHEMA CURRICULO

ALTER SCHEMA CURRICULO TRANSFER [dbo].[CARRERA];
ALTER SCHEMA CURRICULO TRANSFER [dbo].[CERTIFICACION];
ALTER SCHEMA CURRICULO TRANSFER [dbo].[EDUCACION];
ALTER SCHEMA CURRICULO TRANSFER [dbo].[ESTADOESTUDIANTE];
ALTER SCHEMA CURRICULO TRANSFER [dbo].[ESTUDIANTE];
ALTER SCHEMA CURRICULO TRANSFER [dbo].[ESTUDIANTECARRERA];
ALTER SCHEMA CURRICULO TRANSFER [dbo].[EXPERIENCIALABORAL];
ALTER SCHEMA CURRICULO TRANSFER [dbo].[FACULTAD];
ALTER SCHEMA CURRICULO TRANSFER [dbo].[HABILIDAD];
ALTER SCHEMA CURRICULO TRANSFER [dbo].[REFERENCIA];

CREATE SCHEMA OFERTALABORAL

ALTER SCHEMA OFERTALABORAL TRANSFER [dbo].[OFERTALABORAL];
ALTER SCHEMA OFERTALABORAL TRANSFER [dbo].[OFERTALABORALCARRERA];
ALTER SCHEMA OFERTALABORAL TRANSFER [dbo].[POSTULACION];
ALTER SCHEMA OFERTALABORAL TRANSFER [dbo].[VISTASEMPRESAESTUDIANTE];
ALTER SCHEMA OFERTALABORAL TRANSFER [dbo].[EMPRESA];
ALTER SCHEMA OFERTALABORAL TRANSFER [dbo].[DIRECCION];

CREATE SCHEMA SISTEMA

ALTER SCHEMA SISTEMA TRANSFER [dbo].[USUARIO];
ALTER SCHEMA SISTEMA TRANSFER [dbo].[EMPLEADO];
ALTER SCHEMA SISTEMA TRANSFER [dbo].[NIVELEXPERIENCIA];
 */